[GLOBAL]
pants_version = "2.25.0"
backend_packages.add = [
  "pants.backend.python",
  "pants.backend.python.lint.black"
]

[source]
root_patterns = ["/"]

[python]
interpreter_constraints = ["==3.12.*"]
